/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalcrossing;

/**
 *
 * @author jauga
 */
public class FruitSelector extends javax.swing.JFrame
{

    Player player;

    /**
     * Creates new form FruitSelector
     *
     * @param person
     */
    public FruitSelector(Player person)
    {
        initComponents();
        player = person;
        if(player.getNumOfApples() < 1)
        {
            appleButton.setEnabled(false);
        }
        if(player.getNumOfCherry() < 1)
        {
            cherryButton.setEnabled(false);
        }
        if(player.getNumOfPears() < 1)
        {
            pearButton.setEnabled(false);
        }
        if(player.getNumOfPeaches() < 1)
        {
            peachButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        appleButton = new javax.swing.JButton();
        cherryButton = new javax.swing.JButton();
        peachButton = new javax.swing.JButton();
        pearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalcrossing/Apple.png"))); // NOI18N
        appleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                appleButtonActionPerformed(evt);
            }
        });

        cherryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalcrossing/Cherry.png"))); // NOI18N
        cherryButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cherryButtonActionPerformed(evt);
            }
        });

        peachButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalcrossing/Peach.png"))); // NOI18N
        peachButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                peachButtonActionPerformed(evt);
            }
        });

        pearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalcrossing/Pear.png"))); // NOI18N
        pearButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pearButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Which Fruit would you like to consume?");

        jButton1.setText("No fruit");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(10);
        jTextArea2.setRows(4);
        jTextArea2.setText("Increases the\nnumber of wasps\nhit boxes to 2");
        jTextArea2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(10);
        jTextArea3.setRows(4);
        jTextArea3.setText("Increases length of\ntime to catch\nwasps");
        jTextArea3.setAutoscrolls(false);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea5.setColumns(10);
        jTextArea5.setRows(4);
        jTextArea5.setText("Lowers the\nnumber of rounds");
        jTextArea5.setAutoscrolls(false);
        jScrollPane5.setViewportView(jTextArea5);

        jTextArea6.setColumns(10);
        jTextArea6.setRows(4);
        jTextArea6.setText("If the mini game is\nlost the player will\nlose no health");
        jTextArea6.setAutoscrolls(false);
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cherryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(peachButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cherryButton)
                            .addComponent(appleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pearButton)
                            .addComponent(peachButton))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_appleButtonActionPerformed
    {//GEN-HEADEREND:event_appleButtonActionPerformed
        if (player.getNumOfApples() > 0)
        {
            player.eatFruit(Fruit.Apple);
            System.out.println("You've consumed an apple!");
        }
        WaspMiniGame next = new WaspMiniGame(Fruit.Apple, player);
        next.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_appleButtonActionPerformed

    private void cherryButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cherryButtonActionPerformed
    {//GEN-HEADEREND:event_cherryButtonActionPerformed
        if (player.getNumOfCherry() > 0)
        {
            player.eatFruit(Fruit.Cherry);
            System.out.println("You've consumed a cherry!");
        }
        WaspMiniGame next = new WaspMiniGame(Fruit.Cherry, player);
        next.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cherryButtonActionPerformed

    private void peachButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_peachButtonActionPerformed
    {//GEN-HEADEREND:event_peachButtonActionPerformed
        if(player.getNumOfPeaches() > 0)
        {
        player.eatFruit(Fruit.Peach);
        System.out.println("You've consumed a peach!");
        }
        WaspMiniGame next = new WaspMiniGame(Fruit.Peach, player);
        next.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_peachButtonActionPerformed

    private void pearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pearButtonActionPerformed
    {//GEN-HEADEREND:event_pearButtonActionPerformed
        if(player.getNumOfPears() > 0)
        {
        player.eatFruit(Fruit.Pear);
            System.out.println("You've consumed a pear!");
        }
        WaspMiniGame next = new WaspMiniGame(Fruit.Pear, player);
        setVisible(false);
        next.setVisible(true);
    }//GEN-LAST:event_pearButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        WaspMiniGame next = new WaspMiniGame(player);
        setVisible(false);
        next.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appleButton;
    private javax.swing.JButton cherryButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JButton peachButton;
    private javax.swing.JButton pearButton;
    // End of variables declaration//GEN-END:variables
}
